<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="CloudinaryDotNet" Version="1.29.1" />
    <PackageReference Include="dotenv.net" Version="4.0.2" />
    <PackageReference Include="EPPlus" Version="8.5.4" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Minio" Version="7.0.0" />
    <PackageReference Include="QuestPDF" Version="2025.1.0" />
    <PackageReference Include="X.PagedList.Mvc.Core" Version="10.5.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\MyLanguage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MyLanguage.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\MyLanguage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MyLanguage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
